version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  backend:
    image: iamsuslik/kittygram_backend
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: iamsuslik/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static/

  gateway:
    image: iamsuslik/kittygram_gateway
    volumes:
      - static:/staticfiles/
      - media:/media/
      - /etc/nginx/ssl/:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend

volumes:
  pg_data:
  static:
  media:
